version: '3.4'

services:
    tasktracker:
        image: tasktracker
        container_name: TaskTracker
        build:
            context: .
            dockerfile: TaskTracker/Dockerfile
        depends_on: 
            - mssql
        ports:
            - "8443:443"

    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        user: root
        container_name: TaskTracker_SQL
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=dock3rP@ssword
            - MSSQL_AGENT_ENABLED=True
        volumes:
            - TaskTracker_SQL_Volume:/var/opt/mssql/data
        networks:
            - shared

volumes:
    TaskTracker_SQL_Volume:

networks:
  shared:
    name: shared-network
