version: '3.4'

services:
    tasktracker:
        image: tasktracker
        container_name: TaskTracker
        build:
            context: .
            dockerfile: TaskTracker/Dockerfile
        depends_on: 
            - sql_db
        ports:
            - "8443:443"
        networks:
            - shared
    sql_db:
        image: mcr.microsoft.com/mssql/server
        user: root
        container_name: TaskTracker_SQL
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=dock3rP@ssword
        volumes:
            - TaskTracker_SQL_Volume:/var/opt/mssql/data
        networks:
            - shared

volumes:
    TaskTracker_SQL_Volume:

networks:
  shared:
    name: shared-network
